#
# Build qemu/x86_64-softmmu on Debian Bullseye
# Build a debian:bullseye based docker image
#  - Containing the qemu-build
#  - Containing latest CIJOE
#  - envs, guests and scripts for CIJOE
#
# Uses the qemu from https://github.com/qemu/qemu.git tag: 'v6.0.0'
# Uses the latest CIJOE available from PyPI
#
name: refenv.dockerize

on:
  push:
    branches: [ refenv.dockerize ]

# Disable schedule since it is currently not used
#  schedule:
#  - cron:  '15 4,21 * * *'

defaults:
  run:
    shell: bash

jobs:

  build-qemu:

    runs-on: ubuntu-latest
    container: debian:bullseye

    steps:
    - name: Prep, 1..4
      run: |
        apt-get -qy update
        apt-get -qy \
          -o "Dpkg::Options::=--force-confdef" \
          -o "Dpkg::Options::=--force-confold" upgrade
        apt-get -qy install \
          apt-utils \
          aptitude \
          pkg-config
        apt-get -qy autoclean

    - name: Prep, 2..4
      run: |
        aptitude -q -y -f install \
        autoconf \
        automake \
        bc \
        bison \
        bridge-utils \
        build-essential \
        ca-certificates \
        cpio \
        flex \
        gawk \
        git \
        rsync

    - name: Prep, 3..4
      run: |
        aptitude -q -y -f install \
        curl \
        file \
        libaio-dev \
        libglib2.0-0 \
        libglib2.0-dev \
        libguestfs-tools \
        liblzo2-dev \
        libpmem-dev \
        libvirt-dev \
        libvirt0 \
        meson \
        ninja-build \
        python3 \
        python3-dev \
        python3-distutils \
        python3-setuptools \
        texinfo \
        uuid-dev

    - name: Prep, 4..4
      run: |
        aptitude -q -y -f install \
        libpixman-1-0 \
        libpixman-1-dev

    - name: Grab qemu source
      run: |
        git clone --recursive https://github.com/qemu/qemu.git
        cd qemu
        git checkout v6.0.0

    - name: Configure qemu
      run: |
        mkdir build
        mkdir /opt/qemu
        echo "v6.0.0" > /opt/qemu/docker_tag.txt
        cd build
        ../qemu/configure \
            --prefix=/opt/qemu \
            --python=/usr/bin/python3 \
            --audio-drv-list="" \
            --disable-docs \
            --disable-debug-info \
            --disable-opengl \
            --disable-virglrenderer \
            --disable-vte \
            --disable-gtk \
            --disable-sdl \
            --disable-spice \
            --disable-vnc \
            --disable-curses \
            --disable-xen \
            --disable-smartcard \
            --disable-libnfs \
            --disable-libusb \
            --disable-glusterfs \
            --disable-tools \
            --disable-werror \
            --target-list="x86_64-softmmu"

    - name: Build qemu
      run: |
        cd build
        make -j $(nproc)
        make install

    - name: Upload Binaries
      uses: actions/upload-artifact@v2
      with:
        name: qemu-binaries
        path: /opt/qemu

  build-docker:
    needs: build-qemu

    runs-on: ubuntu-latest

    steps:
    - name: Grab sources
      uses: actions/checkout@v2

    - name: Create a docker context
      run: |
        mkdir -p /tmp/docker
        mv envs /tmp/docker/.
        mv guests /tmp/docker/.
        mv scripts /tmp/docker/.

    - name: Grab the qemu binaries
      uses: actions/download-artifact@v2
      with:
        name: qemu-binaries
        path: /tmp/docker/qemu

    - name: Log into docker registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        TAG=$(cat /tmp/docker/qemu/docker_tag.txt)
        docker build \
          -t refenv/qemu-nvme:latest \
          -t refenv/qemu-nvme:${TAG} \
          -f docker/Dockerfile /tmp/docker

    - name: Push Docker image
      run: docker push refenv/qemu-nvme
