name: refenv.testing

on:
  push:
    branches: [ refenv.testing ]

defaults:
  run:
    shell: bash

jobs:

  cijoe-lets-go:

    runs-on: self-hosted
    container:
      image: refenv/qemu-nvme:latest
      options: --privileged

    steps:
    - name: Define stuff
      run: |
        echo "::set-env name=CLOUD_IMG_URL::https://cloud.debian.org/images/cloud/bullseye/daily/20200807-351/debian-11-generic-amd64-daily-20200807-351.qcow2"
        echo "::set-env name=ARTIFACTS::/tmp/artifacts"
        echo "::set-env name=ARTIFACTS_LATEST::/tmp/artifacts/latest"
        echo "::set-env name=RESULTS::/tmp/results"
        echo "::set-env name=RESULTS_LATEST::/tmp/results/latest"
        echo "::set-env name=TARGET_ENV::/opt/envs/localhost-qemu.sh"

    - name: Create result and artifacts directories
      run: |
        mkdir -p ${ARTIFACTS_LATEST}
        mkdir -p ${RESULTS_LATEST}

    - name: Start the SSH server
      run: service ssh restart

    - name: QEMU, provision guest using Debian cloud image
      run: |
        source /opt/scripts/suitup.sh
        qemu::img_from_url "${CLOUD_IMG_URL}"

    - name: QEMU, start the guest
      run: |
        source /opt/scripts/suitup.sh
        qemu::run

    - name: CIJOE, invoke the test-runner targeting the qemu-guest
      run: |
        source /opt/scripts/suitup.sh
        cij_runner \
          $CIJ_TESTPLANS/example_01_usage.plan \
          ${TARGET_ENV} \
          --output ${RESULTS_LATEST}

    - name: QEMU, kill the guest
      run: |
        source /opt/scripts/suitup.sh
        qemu::kill

    - name: CIJOE, result-log-dump on error
      if: failure()
      run: find ${RESULTS} -name "*.log" | xargs cat

    - name: CIJOE, generate test-report
      if: always()
      run: |
        source /opt/scripts/suitup.sh
        cij_reporter ${RESULTS_LATEST}

    - name: CIJOE, upload test results and report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: /tmp/results/*
